### ISSUE TITLE
Naive question about  evaluate

### ISSUE THREAD

**Issue by shusen18** [FunctionLab/selene#108]
Hi,

I want to test the trained model in https://github.com/FunctionLab/selene/blob/master/tutorials/quickstart_training/quickstart_training.ipynb, the used .yml file is shown below:

---
ops: [evaluate]
model: {
    # TODO: update this line with the absolute path to the file.
    path: /root/selene/learn/deeperdeepsea.py,
    class: DeeperDeepSEA,
    class_args: {
        sequence_length: 1000,
        n_targets: 1,
    },
    non_strand_specific: mean
}

sampler: !obj:selene_sdk.samplers.file_samplers.BedFileSampler {
    filepath: /root/selene/learn/training_outputs/test_data.bed,
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: /root/selene/learn/male.hg19.fasta
    },
    n_samples: 1200,
    sequence_length: 1000,
    targets_avail: True,
    n_features: 2,
}

evaluate_model: !obj:selene_sdk.EvaluateModel {
    features:  !obj:selene_sdk.utils.load_features_list {
        input_path: /root/selene/learn/distinct_features.txt
    },
    trained_model_path: /root/selene/learn/training_outputs/best_model.pth.tar,
    n_test_samples: 1200,
    batch_size: 64,
    report_gt_feature_n_positives: 10,
    use_cuda: True,    
}

random_seed: 1447
output_dir: /root/selene/learn/training_outputs
create_subdirectory: False

Then I got this error:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    parse_configs_and_run(configs)
  File "/root/anaconda3/lib/python3.7/site-packages/selene_sdk/utils/config_utils.py", line 341, in parse_configs_and_run
    execute(operations, configs, current_run_output_dir)
  File "/root/anaconda3/lib/python3.7/site-packages/selene_sdk/utils/config_utils.py", line 208, in execute
    evaluate_model = instantiate(evaluate_model_info)
  File "/root/anaconda3/lib/python3.7/site-packages/selene_sdk/utils/config.py", line 239, in instantiate
    return _instantiate_proxy_tuple(proxy, bindings)
  File "/root/anaconda3/lib/python3.7/site-packages/selene_sdk/utils/config.py", line 144, in _instantiate_proxy_tuple
    obj = proxy.callable(**kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/selene_sdk/evaluate_model.py", line 134, in __init__
    if type(self.reference_sequence) == Genome and \
AttributeError: 'EvaluateModel' object has no attribute 'reference_sequence'

Would you like to help me debug? 

Thank you very much!

Yours sincerely,
Shusen

**Comment by evancofer** [comment]
It looks like there was a bug in `evaluate_model.py`. I just submitted PR #110 to fix this problem. With the PR's changes, you shouldn't encounter this problem anymore.

**Comment by kathyxchen** [comment]
Thanks! I have merged @evancofer's PR. We will update conda/pip with a minor release in the next couple weeks to make sure the packages are up-to-date with master. For now, if you need help building the package locally let me know.

**Comment by shusen18** [comment]
@evancofer Thank you very much！ 
It still can not be run properly！

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    parse_configs_and_run(configs)
  File "/root/miniconda3/envs/selene-gpu/lib/python3.6/site-packages/selene_sdk-0.4.1-py3.6-linux-x86_64.egg/selene_sdk/utils/config_utils.py", line 341, in parse_configs_and_run
    execute(operations, configs, current_run_output_dir)
  File "/root/miniconda3/envs/selene-gpu/lib/python3.6/site-packages/selene_sdk-0.4.1-py3.6-linux-x86_64.egg/selene_sdk/utils/config_utils.py", line 208, in execute
    evaluate_model = instantiate(evaluate_model_info)
  File "/root/miniconda3/envs/selene-gpu/lib/python3.6/site-packages/selene_sdk-0.4.1-py3.6-linux-x86_64.egg/selene_sdk/utils/config.py", line 239, in instantiate
    return _instantiate_proxy_tuple(proxy, bindings)
  File "/root/miniconda3/envs/selene-gpu/lib/python3.6/site-packages/selene_sdk-0.4.1-py3.6-linux-x86_64.egg/selene_sdk/utils/config.py", line 144, in _instantiate_proxy_tuple
    obj = proxy.callable(**kwargs)
  File "/root/miniconda3/envs/selene-gpu/lib/python3.6/site-packages/selene_sdk-0.4.1-py3.6-linux-x86_64.egg/selene_sdk/evaluate_model.py", line 134, in __init__
    if (hasattr(self.sampler, reference_sequence) and
NameError: name 'reference_sequence' is not defined

**Comment by evancofer** [comment]
@shusen18 Wow, that was sloppy on my part! Thanks for catching this. I think I used the wrong conda environment to test this, but working on it again now.

**Comment by evancofer** [comment]
It should be fixed now. Just waiting for #111 to be merged.

**Comment by kathyxchen** [comment]
Merged - thank you!

**Comment by shusen18** [comment]
Thank you very much!

The problem is solved！
